// This file is automatically generated. Do not modify it manually.

package main

import (
	"encoding/json"
	"strings"

	"github.com/mattermost/mattermost/server/public/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "sx.paul.mattermost.ntfy",
  "name": "Ntfy Mattermost Server Plugin",
  "description": "A plugin for mattermost server to add notifications via ntfy.",
  "homepage_url": "https://github.com/paul-sx/mattermost-ntfy-plugin",
  "version": "0.4.1",
  "min_server_version": "7.0.0",
  "server": {
    "executables": {
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "darwin-arm64": "server/dist/plugin-darwin-arm64",
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "linux-arm64": "server/dist/plugin-linux-arm64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "settings_schema": {
    "header": "Ntfy Plugin Settings",
    "footer": "These settings are used to configure the Ntfy plugin.",
    "settings": [
      {
        "key": "server_url",
        "display_name": "Ntfy Server URL",
        "type": "text",
        "help_text": "The URL of the Ntfy server to use for notifications.",
        "placeholder": "https://ntfy.sh",
        "default": "",
        "hosting": "",
        "secret": false
      },
      {
        "key": "topic",
        "display_name": "Ntfy Topic",
        "type": "text",
        "help_text": "The topic to use for notifications.",
        "placeholder": "my-topic",
        "default": "",
        "hosting": "",
        "secret": false
      },
      {
        "key": "username",
        "display_name": "Ntfy Username",
        "type": "text",
        "help_text": "The username to use for notifications.",
        "placeholder": "my-username",
        "default": "",
        "hosting": "",
        "secret": false
      },
      {
        "key": "password",
        "display_name": "Ntfy Password",
        "type": "text",
        "help_text": "The password to use for notifications.",
        "placeholder": "",
        "default": "",
        "hosting": "",
        "secret": true
      },
      {
        "key": "active",
        "display_name": "Enable/Disable All Notifications",
        "type": "bool",
        "help_text": "Enable debug logging for the plugin.",
        "placeholder": "",
        "default": false,
        "hosting": "",
        "secret": false
      }
    ],
    "sections": null
  }
}
`

func init() {
	_ = json.NewDecoder(strings.NewReader(manifestStr)).Decode(&manifest)
}
